language: php
php:
 - 5.4
 - 5.5
 - 5.6

branches:
  only:
    - master

before_script:
  - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

services:
  - mongodb

notifications:
  email:
    - hello@withknown.com
